"""初次创建所有表

Revision ID: efe0afbdb5b2
Revises: 
Create Date: 2018-04-14 23:51:41.294321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe0afbdb5b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('logo_url', sa.String(length=128), nullable=True),
    sa.Column('web_site', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_description'), 'company', ['description'], unique=True)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('salary_low', sa.Integer(), nullable=True),
    sa.Column('salary_high', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('exp_req1', sa.String(length=128), nullable=True),
    sa.Column('exp_req2', sa.String(length=128), nullable=True),
    sa.Column('exp_req3', sa.String(length=128), nullable=True),
    sa.Column('exp_req4', sa.String(length=128), nullable=True),
    sa.Column('exp_req5', sa.String(length=128), nullable=True),
    sa.Column('exp_req6', sa.String(length=128), nullable=True),
    sa.Column('exp_req7', sa.String(length=128), nullable=True),
    sa.Column('exp_req8', sa.String(length=128), nullable=True),
    sa.Column('exp_req9', sa.String(length=128), nullable=True),
    sa.Column('exp_req10', sa.String(length=128), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_company_id'), 'job', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_description'), 'job', ['description'], unique=True)
    op.create_index(op.f('ix_job_name'), 'job', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_apply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('degree1', sa.String(length=128), nullable=True),
    sa.Column('degree2', sa.String(length=128), nullable=True),
    sa.Column('degree3', sa.String(length=128), nullable=True),
    sa.Column('degree4', sa.String(length=128), nullable=True),
    sa.Column('degree5', sa.String(length=128), nullable=True),
    sa.Column('career_exp1', sa.String(length=1024), nullable=True),
    sa.Column('career_exp2', sa.String(length=1024), nullable=True),
    sa.Column('career_exp3', sa.String(length=1024), nullable=True),
    sa.Column('career_exp4', sa.String(length=1024), nullable=True),
    sa.Column('career_exp5', sa.String(length=1024), nullable=True),
    sa.Column('career_exp6', sa.String(length=1024), nullable=True),
    sa.Column('career_exp7', sa.String(length=1024), nullable=True),
    sa.Column('cv1_url', sa.String(length=128), nullable=True),
    sa.Column('cv2_url', sa.String(length=128), nullable=True),
    sa.Column('cv3_url', sa.String(length=128), nullable=True),
    sa.Column('cv1_open', sa.Boolean(), nullable=True),
    sa.Column('cv2_open', sa.Boolean(), nullable=True),
    sa.Column('cv3_open', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_info_phone'), 'user_info', ['phone'], unique=False)
    op.create_index(op.f('ix_user_info_user_id'), 'user_info', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_user_id'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_phone'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_table('user_apply')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_job_name'), table_name='job')
    op.drop_index(op.f('ix_job_description'), table_name='job')
    op.drop_index(op.f('ix_job_company_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_description'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
